name: Generate GitHub Metrics

on:
  # Update once a day (06:00 UTC). Adjust if you like.
  schedule:
    - cron: "0 6 * * *"
  # Also let you run it manually each commit to main
  workflow_dispatch:
  push: {branches: ["main"]}

permissions:
  contents: write    # needed to commit the generated svg

concurrency:
  group: metrics
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repo
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # REQUIRED: your username
          user: rolandnyamo

          # Use PAT to avoid strict API limits and enable more plugins
          token: ${{ secrets.METRICS_TOKEN }}

          # Where to save the generated file in your repo
          filename: github-metrics.svg

          # Base sections
          base: header, activity, community, repositories, metadata

          # Common plugins seen in the big dashboard
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 12
          plugin_languages_details: percentage

          plugin_habits: yes
          plugin_habits_from: 200       # commits to sample for “habits”
          plugin_habits_days: 14

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_lines: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_topics: yes
          plugin_notable: yes

      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add github-metrics.svg
            git commit -m "chore: update metrics"
            git push
          fi